name: 'RevoGuild'
main: 'net.karolek.revoguild.GuildPlugin'
version: '${project.version}'
authors: [Karolek, kamcio96]
website: 'http://karolek.net/plugins/revoguild'
description: '${project.description}'
